version: "3.2"
services:
  ejabberd_service:
    privileged: true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 165536
        hard: 165536
    cap_add:
      - ALL
    # logging default settings from /etc/docker/daemon.json
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

    image: ejabberd/ecs:18.01
    container_name: ejabberd-server
    volumes:
      - ./log/ejabberd:/home/ejabberd/logs/
      - ./data/database:/home/ejabberd/database/
      - ./config/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    environment:
      - XMPP_DOMAIN=ejabberd.local
      - ERLANG_NODE=ejabberdcd
    network_mode: host